language: rust

matrix:
  include:
    # -------------------------------------------------
    # Linux distributions
    # -------------------------------------------------
    #
    # + Trusty (nightly, stable, beta)
    #   Distribution: Ubuntu 14
    - os: linux
      dist: trusty
      env: TARGET=x86_64-unknown-linux-gnu
      rust: nightly

    - os: linux
      dist: trusty
      env: TARGET=x86_64-unknown-linux-gnu
      rust: beta

    - os: linux
      dist: trusty
      env: TARGET=x86_64-unknown-linux-gnu
      rust: stable

    # + xenial (only stable rust)
    # Distribution: Ubuntu 16 
    - os: linux
      dist: xenial
      env: TARGET=x86_64-unknown-linux-gnu
      rust: stable

    # + precise (only stable rust)
    # Very old distribution (deprecated)
    - os: linux
      dist: precise
      env: TARGET=x86_64-unknown-linux-gnu
      rust: stable

    # + OSX / Darwin (nightly, stable, beta)
    - os: osx
      env: TARGET=i686-apple-darwin
      rust: nightly

    - os: osx
      env: TARGET=i686-apple-darwin
      rust: beta

    - os: osx
      env: TARGET=i686-apple-darwin
      rust: stable

before_install: set -e

install:
  - bash ci/install.sh

script:
  - bash ci/script.sh

after_script: set +e

cache: cargo

before_cache:
  - chmod -R a+r $HOME/.cargo;

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/196d37e7f965d6bd599d
    on_success: always
    on_failure: always
    on_start: always
