language: rust

matrix:
  include:
    - os: linux
      env: TARGET=x86_64-unknown-linux-gnu
      rust: nightly

    - os: linux
      env: TARGET=x86_64-unknown-linux-gnu
      rust: beta

    - os: linux
      dist: trusty
      env: TARGET=x86_64-unknown-linux-gnu
      rust: stable

    - os: linux
      dist: xenial
      env: TARGET=x86_64-unknown-linux-gnu
      rust: stable

    - os: osx
      env: TARGET=i686-apple-darwin
      rust: stable

before_install: set -e

install:
  - bash ci/install.sh

script:
  - bash ci/script.sh

after_script: set +e

cache: cargo

before_cache:
  - chmod -R a+r $HOME/.cargo;

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/196d37e7f965d6bd599d
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: always     # options: [always|never|change] default: always
