[package]
authors = ["Emil Fresk <emil.fresk@gmail.com>"]
categories = ["embedded", "nonlinear", "optimization"]
keywords = ["embedded", "optimization", "solver"]
description = "A Rust implementation of the PANOC nonlinear optimization solver"
documentation = "https://docs.rs/panoc"
license = "MIT OR Apache-2.0"
readme = "README.md"
name = "panoc-rs"
version = "0.1.0"

[dependencies]
num = "0.2.0"
lipschitz_estimator = {path = "../lipschitz_estimator"}
lbfgs = {path = "../lbfgs-rs"}
