# This action generates the documentation and then deploys it to the `gh-pages` branch.

name: Documentation

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
    # Checks-out the repository under $GITHUB_WORKSPACE
    - uses: actions/checkout@v2

    # Install Python dependencies to generate tests
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9.2'
    - name: Install Python Dependencies
      run: |
        pip install sphinx
        pip install sphinx-rtd-theme

    # - name: Create staging area
    #   run: |
    #     rm -rf /tmp/staging
    #     mkdir -p /tmp/staging
    #     cp -r sphinx-dox /tmp/staging
    #     cp -r open-codegen/opengen /tmp/staging
    #     # git fetch origin gh-pages:gh-pages ||:
    #     # git checkout gh-pages

    - name: Build documentation
      run: |
        rm -rf sphinx
        mkdir -p sphinx
        cd sphinx-dox
        make html
        cp -r build/
        

