# GitHub Action
# Builds sphinx documentation and pushes it to gh-pages

name: Documentation

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    # Install sphinx
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9.2'
    - name: Install Python Dependencies
      run: |
        pip install sphinx
        pip install sphinx-rtd-theme

    - name: GHPages preparation
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        current_branch=$(git rev-parse --abbrev-ref HEAD)
        git fetch origin gh-pages:gh-pages || :
        git checkout gh-pages
        git rm -r api-dox/
        git checkout $(current_branch)

    - name: Build documentation
      run: |
        rm -rf sphinx
        mkdir -p sphinx
        cd sphinx-dox
        sphinx-apidoc -o ./source/ ../open-codegen/opengen ../open-codegen/opengen/test/
        make html
        cp -r build/html/ ../sphinx

    - name: Transfer files to gh-pages
      run: |
        cd $GITHUB_WORKSPACE/
        rm -rf api-dox/
        mv sphinx/ api-dox/
        git checkout gh-pages
        git add api-dox/
        git commit -m "documentation"
        git push origin gh-pages || :
